import{useCallback,useEffect,useMemo,useRef,useState}from'react';import{Expand,Minimize,Heart,Sparkles}from'lucide-react';import{indexAt,PLAYER_COLORS}from'./engine';import{labels,promptBank}from'./data/prompts';import type{Kind,Level,Prompt}from'./types';
type Page='home'|'level'|'players'|'playerWheel'|'kind'|'promptWheel'|'result'|'final';
interface Game{page:Page;level?:Level;players:number;playerAngle:number;truthAngle:number;dareAngle:number;player?:number;kind?:Kind;prompt?:Prompt;first?:Prompt}
const fresh:Game={page:'home',players:4,playerAngle:0,truthAngle:0,dareAngle:0};
const load=()=>{try{return JSON.parse(sessionStorage.getItem('tod-game')||'null')||fresh}catch{return fresh}};
function Wheel({count,angle,labels:items,colors}: {count:number;angle:number;labels:string[];colors:string[]}){const size=500,c=250,r=238;return <svg className="wheel" viewBox="0 0 500 500" aria-label={`${count}格转盘`}><g>{Array.from({length:count},(_,i)=>{const w=360/count,a0=(i*w-w/2-90)*Math.PI/180,a1=(i*w+w/2-90)*Math.PI/180;const path=`M${c},${c} L${c+r*Math.cos(a0)},${c+r*Math.sin(a0)} A${r},${r} 0 ${w>180?1:0} 1 ${c+r*Math.cos(a1)},${c+r*Math.sin(a1)} Z`;const mid=(i*w-90)*Math.PI/180;return <g key={i}><path d={path} fill={colors[i%colors.length]} stroke="#fff" strokeWidth={count>20?.45:2}/>{count<=20?<text x={c+r*.7*Math.cos(mid)} y={c+r*.7*Math.sin(mid)} textAnchor="middle" dominantBaseline="middle" fill="#fff" fontWeight="900" fontSize={Math.max(18,42-count)} transform={`rotate(${i*w},${c+r*.7*Math.cos(mid)},${c+r*.7*Math.sin(mid)})`}>{items[i]}</text>:<text className="tiny" x="280" y="251" transform={`rotate(${i*w-90} 250 250)`}>{items[i]}</text>}</g>})}</g><g transform={`rotate(${angle} 250 250)`}><line x1="250" y1="250" x2="250" y2="25" stroke="#202334" strokeWidth="5"/><path d="M250 12l-10 24h20z" fill="#202334"/></g><circle cx="250" cy="250" r="22" fill="#fff" stroke="#202334" strokeWidth="7"/></svg>}
function App(){const[g,setG]=useState<Game>(load);const[spinning,setSpinning]=useState(false);const[exit,setExit]=useState(false);const[error,setError]=useState('');const[full,setFull]=useState(!!document.fullscreenElement);const raf=useRef(0);const stop=useRef<(()=>void)|null>(null);
 useEffect(()=>{sessionStorage.setItem('tod-game',JSON.stringify(g))},[g]);useEffect(()=>{const f=()=>setFull(!!document.fullscreenElement);document.addEventListener('fullscreenchange',f);return()=>document.removeEventListener('fullscreenchange',f)},[]);useEffect(()=>()=>cancelAnimationFrame(raf.current),[]);
 const patch=(v:Partial<Game>)=>setG(x=>({...x,...v}));const angleKey=g.page==='playerWheel'?'playerAngle':g.kind==='truth'?'truthAngle':'dareAngle';
 const spin=useCallback((forced=false)=>{if(spinning)return;setSpinning(true);const start=performance.now(),initial=g[angleKey] as number;const duration=forced?3000+Math.random()*2000:10000;const d=.75+Math.random()*.5;let stopping=forced;let stopAt=duration;let speed=0,last=start,total=initial;stop.current=()=>{if(!stopping){stopping=true;stopAt=performance.now()-start+d*1000}};const tick=(now:number)=>{const elapsed=now-start,dt=(now-last)/1000;last=now;if(!stopping&&elapsed<d*1000)speed=720*(3*(elapsed/d/1000)**2-2*(elapsed/d/1000)**3);else if(!stopping)speed=720;if(!stopping&&elapsed>=duration-d*1000){stopping=true;stopAt=duration}if(stopping){const remain=Math.max(0,(stopAt-elapsed)/(d*1000));speed=Math.min(speed,720*(3*remain**2-2*remain**3))}total+=speed*dt;patch({[angleKey]:total});if(elapsed<stopAt){raf.current=requestAnimationFrame(tick)}else{setSpinning(false);const final=total;patch({[angleKey]:final});if(g.page==='playerWheel'){const p=indexAt(final,g.players)+1;setTimeout(()=>patch({page:'kind',player:p}),2000)}else{const list=promptBank[g.level!][g.kind!];let item=list[indexAt(final,100)];if(forced&&item.id===g.first?.id)item=list[(indexAt(final,100)+1)%100];setTimeout(()=>patch({page:forced?'final':'result',prompt:item}),forced?2000:0)}}};raf.current=requestAnimationFrame(tick)},[spinning,g,angleKey]);
 const quit=()=>{cancelAnimationFrame(raf.current);sessionStorage.removeItem('tod-game');setG(fresh);setSpinning(false);setExit(false)};const inGame=g.page!=='home';const prompts=g.level&&g.kind?promptBank[g.level][g.kind]:[];const angle=g[angleKey] as number;
 return <main className={`app page-${g.page}`}><button className="fullscreen" aria-label="切换全屏" onClick={()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen()}>{full?<Minimize/>:<Expand/>}</button>{inGame&&<button className="exit" aria-label="退出游戏" onClick={()=>setExit(true)}>×</button>}
 {g.page==='home'&&<section className="hero"><span className="sticker one">今晚不许躲</span><Heart className="heart"/><Sparkles className="spark"/><p className="eyebrow">PARTY GAME</p><h1>真心话<br/><b>大冒险</b></h1><p>转动指针，让今晚多一点心跳。</p><button className="primary" onClick={()=>patch({page:'level'})}>开始游戏 <span>→</span></button></section>}
 {g.page==='level'&&<section className="panel"><p className="eyebrow">CHOOSE YOUR VIBE</p><h2>今晚，想玩到哪一步？</h2><div className="levels">{(['sweet','flirty','wild']as Level[]).map((x,i)=><button key={x} className={`level l${i}`} onClick={()=>patch({level:x,page:'players'})}><b>{['🌱','💗','🔥'][i]} {labels[x]}</b><span>{['轻松有趣，笑声刚刚好','心跳升温，距离近一点','突破边界，大胆玩起来'][i]}</span><i>选择此档 →</i></button>)}</div></section>}
 {g.page==='players'&&<section className="panel players"><p className="eyebrow">HOW MANY PLAYERS?</p><h2>有多少位冒险家？</h2><p>输入 2—20 人，我们会为每个人分配专属颜色。</p><form onSubmit={e=>{e.preventDefault();if(!Number.isInteger(g.players)||g.players<2||g.players>20){setError('请输入 2—20 之间的整数');return}setError('');patch({page:'playerWheel'})}}><button type="button" onClick={()=>patch({players:Math.max(2,g.players-1)})}>−</button><input aria-label="玩家人数" type="number" value={g.players} onChange={e=>patch({players:Number(e.target.value)})}/><button type="button" onClick={()=>patch({players:Math.min(20,g.players+1)})}>＋</button><button className="primary" type="submit">准备好了 →</button></form>{error&&<p className="error">{error}</p>}</section>}
 {(g.page==='playerWheel'||g.page==='promptWheel')&&<section className="wheelpage"><header><p className="eyebrow">{g.page==='playerWheel'?'WHO’S NEXT?':g.kind==='truth'?'TRUTH TIME':'DARE TIME'}</p><h2>{g.page==='playerWheel'?'转动指针，选出下一位':g.kind==='truth'?'真心话时间':'大冒险时间'}</h2><p>{spinning?'指针正在寻找命运…':'点击任一侧按钮开始'}</p></header><div className="wheelrow">{!g.first&&<button className={`side left ${spinning?'pause':''}`} disabled={spinning&&!!stop.current&&false} onClick={()=>spinning?stop.current?.():spin()}>{spinning?'暂停':'开始'}</button>}<Wheel count={g.page==='playerWheel'?g.players:100} angle={angle} labels={g.page==='playerWheel'?Array.from({length:g.players},(_,i)=>String(i+1)):prompts.map(x=>x.text)} colors={g.page==='playerWheel'?PLAYER_COLORS:['#f7a8b8','#7ed6d0','#f7ca6b','#9fa8e8','#dda0cf']}/>{!g.first&&<button className={`side right ${spinning?'pause':''}`} onClick={()=>spinning?stop.current?.():spin()}>{spinning?'暂停':'开始'}</button>}</div></section>}
 {g.page==='kind'&&<><section className="wheelpage dim"><Wheel count={g.players} angle={g.playerAngle} labels={Array.from({length:g.players},(_,i)=>String(i+1))} colors={PLAYER_COLORS}/></section><div className="shade"><section className="modal choose"><h2><em style={{color:PLAYER_COLORS[(g.player!-1)%20]}}>{g.player}号</em> 请你选择：</h2><div><button onClick={()=>patch({kind:'truth',page:'promptWheel'})}>真心话<span>说出秘密</span></button><button onClick={()=>patch({kind:'dare',page:'promptWheel'})}>大冒险<span>接受挑战</span></button></div></section></div></>}
 {g.page==='result'&&<div className="shade"><section className="modal result"><p className="eyebrow">YOUR CHALLENGE</p><h2>{g.prompt?.text}</h2><div><button className="done" onClick={()=>patch({page:'playerWheel',player:undefined,kind:undefined,prompt:undefined,first:undefined})}>完成</button><button className="red" onClick={()=>{patch({page:'promptWheel',first:g.prompt});setTimeout(()=>spin(true),0)}}>重抽</button></div><small>重抽只有一次机会，选择后选择权将不在您的手中</small></section></div>}
 {g.page==='final'&&<section className="final"><p>最终挑战</p><h2>{g.prompt?.text}</h2><button className="done" onClick={()=>patch({page:'playerWheel',player:undefined,kind:undefined,prompt:undefined,first:undefined})}>已完成</button></section>}
 {exit&&<div className="shade top"><section className="modal confirm"><h2>是否退出</h2><div><button onClick={quit}>确定</button><button onClick={()=>setExit(false)}>取消</button></div></section></div>}</main>}
export default App;
